"""Target-specific B2B partnership offers. No medical outcome guarantees."""
OFFERS={
"hbot_sports":{"name":"Rescu Athlete Recovery Partnership","hook":"Give your athletes a physician-led recovery destination without adding equipment, staff, or another room.","stack":["Priority pathway for referred athletes","HBOT and recovery-service navigation based on appropriate evaluation","Coordinated scheduling through one Rescu contact","Partner education and co-branded recovery day option"],"cta":"Reply PARTNER and we'll map a simple pilot for your athletes."},
"ortho_pt":{"name":"Rescu Recovery Extension","hook":"Keep your team focused on rehab while Rescu becomes the optional recovery destination around the plan you already lead.","stack":["Physician-led intake when appropriate","Access to Rescu recovery modalities","Simple referral handoff","Progress communication only with appropriate authorization"],"cta":"Reply RECOVERY and we'll build the referral pathway with you."},
"pelvic_floor":{"name":"Pelvic Floor Support Partnership","hook":"Give appropriate clients another physician-led option to explore without adding equipment or operational burden to your practice.","stack":["Rescu consultation pathway","Emsella education and navigation","Simple handoff back to the referring practice","Dedicated scheduling contact"],"cta":"Reply PELVIC and we'll set up a 15-minute partnership call."},
"fitness":{"name":"Rescu Performance Partner","hook":"Add a recovery destination to your member experience without buying recovery equipment or staffing another department.","stack":["Member recovery pathway","Performance and recovery orientation","Partner activation day option","Dedicated booking route"],"cta":"Reply PERFORMANCE and we'll design a pilot for your members."},
"clubs":{"name":"Rescu Club Recovery Partnership","hook":"Give members and athletes a premium local recovery option without changing your club operations.","stack":["Member recovery pathway","Team or club orientation","Optional recovery event","Dedicated concierge handoff"],"cta":"Reply CLUB and we'll build the first activation."},
"aesthetics":{"name":"Rescu Aesthetics Collaboration","hook":"Create a physician-led destination for complementary noninvasive aesthetic services without adding another device platform.","stack":["TriLift and RF microneedling navigation","Simple referral pathway","Collaboration opportunities","Dedicated Rescu contact"],"cta":"Reply AESTHETICS and we'll map the collaboration."},
"corporate":{"name":"Rescu Executive Reset","hook":"Give your team a local wellness and recovery destination with minimal administrative lift.","stack":["Curated employee experience","Scheduling concierge","Optional onsite education or activation","Scalable individual pathways"],"cta":"Reply RESET and we'll design a pilot for your team."},
"ozone_referral":{"name":"Rescu Physician-Led Wellness Referral Pathway","hook":"Give appropriate patients a physician-led destination to explore Rescu wellness services while you remain their primary clinician.","stack":["Physician consultation pathway","Clear scope and navigation","Dedicated scheduling handoff","Referral relationship built around appropriate use"],"cta":"Reply CONNECT and we'll set up the referral pathway."}
}
def offer_for(campaign): return OFFERS[campaign]
